[monday]
classes = ["ATL", "BIO", "MT", "MT", "PA", "CHEM", "ENGLISH", "SPANISH", "POCSO"]

[tuesday]
classes = ["CT", "MATHS", "SPANISH", "PE", "PE", "ENG", "PHY", "S SC", "SSC"]

[wednesday]
classes = ["MSP", "SSC", "ENGLISH", "MATHS", "SPANISH", "SPANISH", "LIB", "MATHS", "CHEM"]

[thursday]
classes = ["ASSEMBLY", "CT", "MATHS", "SSC", "MATHS", "ENGLISH", "ENGLISH", "AI", "VA", "PHY"]

[friday]
classes = ["CT", "S SC", "SSC", "MATHS", "MATHS", "SSC", "VEC", "VEC", "SPANISH", "BIO", "BIO"]
